blueprint:
  name: Hue Tap Dial
  domain: automation
  input:
    mqtt_topic:
      name: MQTT Topic
      selector:
        text:
    tap_counter:
      name: Counter Helper
      selector:
        entity:
          domain: counter
    last_pressed:
      name: Last Pressed Helper
      selector:
        entity:
          domain: input_text
    button_1_single_press:
      name: Button 1 Single Press
      default: []
      selector:
        action:
    button_1_double_press:
      name: Button 1 Double Press
      default: []
      selector:
        action:
    button_1_hold:
      name: Button 1 Hold
      default: []
      selector:
        action:
    button_2_single_press:
      name: Button 2 Single Press
      default: []
      selector:
        action:
    button_2_double_press:
      name: Button 2 Double Press
      default: []
      selector:
        action:
    button_2_hold:
      name: Button 2 Hold
      default: []
      selector:
        action:
    button_3_single_press:
      name: Button 3 Single Press
      default: []
      selector:
        action:
    button_3_double_press:
      name: Button 3 Double Press
      default: []
      selector:
        action:
    button_3_hold:
      name: Button 3 Hold
      default: []
      selector:
        action:
    button_4_single_press:
      name: Button 4 Single Press
      default: []
      selector:
        action:
    button_4_double_press:
      name: Button 4 Double Press
      default: []
      selector:
        action:
    button_4_hold:
      name: Button 4 Hold
      default: []
      selector:
        action:

mode: parallel
max: 10
max_exceeded: silent

trigger:
  - platform: mqtt
    topic: !input mqtt_topic

condition:
  - condition: template
    value_template: "{{ trigger.payload_json.action != '' }}"

action:
  - variables:
      button: "{{ trigger.payload_json.action | regex_replace(find='[^1-4]', replace='') }}"
      action_type: "{{ trigger.payload_json.action }}"
      last_button: "{{ states(last_pressed) }}"
      press_count: "{{ states(tap_counter) }}"

  - choose:
      # Handle initial button press
      - conditions:
          - condition: template
            value_template: "{{ action_type is match('^button_[1-4]_press$') }}"
        sequence:
          - condition: template
            value_template: "{{ button != states(last_pressed) }}"
          - service: counter.reset
            target:
              entity_id: !input tap_counter
          - service: input_text.set_value
            target:
              entity_id: !input last_pressed
            data:
              value: "{{ button }}"
          - service: counter.increment
            target:
              entity_id: !input tap_counter
          - delay:
              seconds: 1
          - service: counter.reset
            target:
              entity_id: !input tap_counter

      # Handle double press actions
      - conditions:
          - condition: template
            value_template: "{{ action_type is match('button_[1-4]_press_release') and states(tap_counter) > '1' }}"
        sequence:
          - choose:
              - conditions:
                  - condition: template
                    value_template: "{{ action_type == 'button_1_press_release' }}"
                sequence: !input button_1_double_press
              - conditions:
                  - condition: template
                    value_template: "{{ action_type == 'button_2_press_release' }}"
                sequence: !input button_2_double_press
              - conditions:
                  - condition: template
                    value_template: "{{ action_type == 'button_3_press_release' }}"
                sequence: !input button_3_double_press
              - conditions:
                  - condition: template
                    value_template: "{{ action_type == 'button_4_press_release' }}"
                sequence: !input button_4_double_press

    default:
      - choose:
          # Handle single press actions
          - conditions:
              - condition: template
                value_template: "{{ action_type is match('button_[1-4]_press_release') }}"
            sequence:
              - delay:
                  milliseconds: 250
              - condition: template
                value_template: "{{ states(tap_counter) > '1' }}"
              - service: script.stop
                data:
                  message: "Double tap detected"
              - choose:
                  - conditions:
                      - condition: template
                        value_template: "{{ action_type == 'button_1_press_release' }}"
                    sequence: !input button_1_single_press
                  - conditions:
                      - condition: template
                        value_template: "{{ action_type == 'button_2_press_release' }}"
                    sequence: !input button_2_single_press
                  - conditions:
                      - condition: template
                        value_template: "{{ action_type == 'button_3_press_release' }}"
                    sequence: !input button_3_single_press
                  - conditions:
                      - condition: template
                        value_template: "{{ action_type == 'button_4_press_release' }}"
                    sequence: !input button_4_single_press

          # Handle hold actions
          - conditions:
              - condition: template
                value_template: "{{ action_type == 'button_1_hold' }}"
            sequence: !input button_1_hold
          - conditions:
              - condition: template
                value_template: "{{ action_type == 'button_2_hold' }}"
            sequence: !input button_2_hold
          - conditions:
              - condition: template
                value_template: "{{ action_type == 'button_3_hold' }}"
            sequence: !input button_3_hold
          - conditions:
              - condition: template
                value_template: "{{ action_type == 'button_4_hold' }}"
            sequence: !input button_4_hold
