blueprint:
  name: Hue Tap Dial Dimmer
  domain: automation
  input:
    mqtt_topic:
      name: MQTT Topic
      description: Topic of the Philips Hue Tap Dial Switch
      default: zigbee2mqtt/<device name>
    light_entity:
      name: Light Entity
      description: The light entity to control
      selector:
        entity:
          domain: light

mode: parallel
max: 10
max_exceeded: silent

trigger:
  - platform: mqtt
    topic: !input mqtt_topic

variables:
  action: "{{ trigger.payload_json.action }}"
  changes:
    dial_rotate_right_step: 3
    dial_rotate_right_slow: 7
    dial_rotate_right_fast: 40
    dial_rotate_left_step: -3
    dial_rotate_left_slow: -7
    dial_rotate_left_fast: -40
    brightness_step_up: 10
    brightness_step_down: -10

condition:
  - condition: template
    value_template: "{{ action in changes }}"

action:
  - service: light.turn_on
    target:
      entity_id: !input light_entity
    data:
      brightness_step_pct: "{{ changes[action] }}"
