blueprint:
  name: Hue Tap Dial Advanced 2
  description: Control lights and covers with a Hue Tap Dial Switch with configurable dimming speeds
  domain: automation
  input:
    # [Previous inputs remain the same until dimming values]

    # Dimming Values
    dim_step:
      name: Step Dimming Value
      description: Brightness change for step rotation (1-100)
      default: 3
      selector:
        number:
          min: 1
          max: 100
          unit_of_measurement: "%"
    dim_slow:
      name: Slow Dimming Value
      description: Brightness change for slow rotation (1-100)
      default: 7
      selector:
        number:
          min: 1
          max: 100
          unit_of_measurement: "%"
    dim_fast:
      name: Fast Dimming Value
      description: Brightness change for fast rotation (1-100)
      default: 15
      selector:
        number:
          min: 1
          max: 100
          unit_of_measurement: "%"
    dim_step_brightness:
      name: Brightness Step Value
      description: Brightness change for brightness step (1-100)
      default: 10
      selector:
        number:
          min: 1
          max: 100
          unit_of_measurement: "%"

    # [Rest of the inputs remain the same]

triggers:
  - topic: !input mqtt_topic
    trigger: mqtt

variables:
  action: "{{ trigger.payload_json.action }}"

actions:
  - choose:
      # [Previous button actions remain the same]

      # Rotation handling - FIXED VERSION
      - conditions:
          - condition: template
            value_template: "{{ action is match 'dial_rotate_.*' }}"
        sequence:
          - variables:
              brightness_change: >
                {% set step = input.dim_step | int %}
                {% set slow = input.dim_slow | int %}
                {% set fast = input.dim_fast | int %}
                {% set brightness = input.dim_step_brightness | int %}
                {% if action == 'dial_rotate_right_step' %}
                  {{ step }}
                {% elif action == 'dial_rotate_right_slow' %}
                  {{ slow }}
                {% elif action == 'dial_rotate_right_fast' %}
                  {{ fast }}
                {% elif action == 'dial_rotate_left_step' %}
                  {{ -step }}
                {% elif action == 'dial_rotate_left_slow' %}
                  {{ -slow }}
                {% elif action == 'dial_rotate_left_fast' %}
                  {{ -fast }}
                {% elif action == 'brightness_step_up' %}
                  {{ brightness }}
                {% elif action == 'brightness_step_down' %}
                  {{ -brightness }}
                {% else %}
                  0
                {% endif %}
              target_lights: >
                {% set button = states('input_text.lichtschalter_wohnzimmer_last_button') %}
                {% if button == '1' %}
                  {{ input.button_1_lights.entity_id }}
                {% elif button == '2' %}
                  {{ input.button_2_lights.entity_id }}
                {% elif button == '3' %}
                  {{ input.button_3_lights.entity_id }}
                {% else %}
                  {{ input.button_1_lights.entity_id }}
                {% endif %}
          - target:
              entity_id: "{{ target_lights }}"
            action: light.turn_on
            data:
              transition: 1
              brightness_step_pct: "{{ brightness_change }}"
