blueprint:
  name: Hue Tap Dial Dimmer
  domain: automation
  input:
    mqtt_topic:
      name: MQTT Topic
      description: Topic of the Philips Hue Tap Dial Switch
      default: zigbee2mqtt/<device name>
    light_entity:
      name: Light Entity
      description: The light entity to control
      selector:
        entity:
          domain: light
    # RIGHT actions
    dial_rotate_right_step:
      name: Dial Rotate Right Step
      description: Brightness change for dial_rotate_right_step event
      default: 3
      selector:
        number:
          min: 1
          max: 100
          unit_of_measurement: "%"
    dial_rotate_right_slow:
      name: Dial Rotate Right Slow
      description: Brightness change for dial_rotate_right_slow event
      default: 7
      selector:
        number:
          min: 1
          max: 100
          unit_of_measurement: "%"
    brightness_step_up:
      name: Brightness Step Up
      description: Brightness change for brightness_step_up event
      default: 10
      selector:
        number:
          min: 1
          max: 100
          unit_of_measurement: "%"
    dial_rotate_right_fast:
      name: Dial Rotate Right Fast
      description: Brightness change for dial_rotate_right_fast event
      default: 40
      selector:
        number:
          min: 1
          max: 100
          unit_of_measurement: "%"
    # LEFT actions
    dial_rotate_left_step:
      name: Dial Rotate Left Step
      description: Brightness change for dial_rotate_left_step event
      default: -3
      selector:
        number:
          min: -100
          max: -1
          unit_of_measurement: "%"
    dial_rotate_left_slow:
      name: Dial Rotate Left Slow
      description: Brightness change for dial_rotate_left_slow event
      default: -7
      selector:
        number:
          min: -100
          max: -1
          unit_of_measurement: "%"
    brightness_step_down:
      name: Brightness Step Down
      description: Brightness change for brightness_step_down event
      default: -10
      selector:
        number:
          min: -100
          max: -1
          unit_of_measurement: "%"
    dial_rotate_left_fast:
      name: Dial Rotate Left Fast
      description: Brightness change for dial_rotate_left_fast event
      default: -40
      selector:
        number:
          min: -100
          max: -1
          unit_of_measurement: "%"

mode: parallel
max: 10
max_exceeded: silent

trigger:
  - platform: mqtt
    topic: !input mqtt_topic

variables:
  action: "{{ trigger.payload_json.action }}"
  changes:
    dial_rotate_right_step: !input dial_rotate_right_step
    dial_rotate_right_slow: !input dial_rotate_right_slow
    brightness_step_up: !input brightness_step_up
    dial_rotate_right_fast: !input dial_rotate_right_fast
    dial_rotate_left_step: !input dial_rotate_left_step
    dial_rotate_left_slow: !input dial_rotate_left_slow
    brightness_step_down: !input brightness_step_down
    dial_rotate_left_fast: !input dial_rotate_left_fast

condition:
  - condition: template
    value_template: "{{ action in changes }}"

action:
  - service: light.turn_on
    target:
      entity_id: !input light_entity
    data:
      brightness_step_pct: "{{ changes[action] }}"
