blueprint:
  name: Hue Tap Dial Dimmer
  domain: automation
  input:
    mqtt_topic:
      name: MQTT Topic
      description: Topic of the Philips Hue Tap Dial Switch
      default: zigbee2mqtt/<device name>
    light_entity:
      name: Light Entity
      description: The light entity to control
      selector:
        entity:
          domain: light
    step_value:
      name: Step Value
      description: Brightness change percentage for step rotation (right/left)
      default: 3
      selector:
        number:
          min: 1
          max: 100
          unit_of_measurement: "%"
    right_slow:
      name: Right Slow Value
      description: Brightness change percentage for slow right rotation
      default: 7
      selector:
        number:
          min: 1
          max: 100
          unit_of_measurement: "%"
    step_up:
      name: Step Up Value
      description: Brightness change percentage for step up
      default: 10
      selector:
        number:
          min: 1
          max: 100
          unit_of_measurement: "%"
    right_fast:
      name: Right Fast Value
      description: Brightness change percentage for fast right rotation
      default: 40
      selector:
        number:
          min: 1
          max: 100
          unit_of_measurement: "%"

mode: parallel
max: 10
max_exceeded: silent

trigger:
  - platform: mqtt
    topic: !input mqtt_topic

variables:
  action: "{{ trigger.payload_json.action }}"
  changes:
    dial_rotate_right_step: !input step_value
    dial_rotate_left_step: "{{ -1 * step_value }}"
    dial_rotate_right_slow: !input right_slow
    dial_rotate_left_slow: "{{ -1 * right_slow }}"
    brightness_step_up: !input step_up
    brightness_step_down: "{{ -1 * step_up }}"
    dial_rotate_right_fast: !input right_fast
    dial_rotate_left_fast: "{{ -1 * right_fast }}"

condition:
  - condition: template
    value_template: "{{ action in changes }}"

action:
  - service: light.turn_on
    target:
      entity_id: !input light_entity
    data:
      brightness_step_pct: "{{ changes[action] }}"
