blueprint:
  name: Shelly Cover Controls (Multi-Device)
  description: Control covers using Shelly devices with support for multiple devices and all button actions
  domain: automation
  input:
    shelly_devices:
      name: Shelly Devices
      description: Select the Shelly devices to use for button control
      selector:
        device:
          integration: shelly
          multiple: true

    # Common actions for both buttons
    single_press_action:
      name: Single Press Action
      description: Action to run on single press (both buttons)
      default: []
      selector:
        action: {}
    double_press_action:
      name: Double Press Action
      description: Action to run on double press (both buttons)
      default: []
      selector:
        action: {}
    triple_press_action:
      name: Triple Press Action
      description: Action to run on triple press (both buttons)
      default: []
      selector:
        action: {}
    long_press_action:
      name: Long Press Action
      description: Action to run on long press (both buttons)
      default: []
      selector:
        action: {}
    btn_up_action:
      name: Button Up Action
      description: Action to run when button is released (both buttons)
      default: []
      selector:
        action: {}
    btn_down_action:
      name: Button Down Action
      description: Action to run when button is pressed down (both buttons)
      default: []
      selector:
        action: {}

mode: single

trigger:
  # Button 1 Triggers
  - platform: device
    domain: shelly
    type: single_push
    subtype: button1
    device_id: !input shelly_devices
    id: single
  - platform: device
    domain: shelly
    type: double_push
    subtype: button1
    device_id: !input shelly_devices
    id: double
  - platform: device
    domain: shelly
    type: triple_push
    subtype: button1
    device_id: !input shelly_devices
    id: triple
  - platform: device
    domain: shelly
    type: long_push
    subtype: button1
    device_id: !input shelly_devices
    id: long
  - platform: device
    domain: shelly
    type: btn_up
    subtype: button1
    device_id: !input shelly_devices
    id: btn_up
  - platform: device
    domain: shelly
    type: btn_down
    subtype: button1
    device_id: !input shelly_devices
    id: btn_down

  # Button 2 Triggers
  - platform: device
    domain: shelly
    type: single_push
    subtype: button2
    device_id: !input shelly_devices
    id: single
  - platform: device
    domain: shelly
    type: double_push
    subtype: button2
    device_id: !input shelly_devices
    id: double
  - platform: device
    domain: shelly
    type: triple_push
    subtype: button2
    device_id: !input shelly_devices
    id: triple
  - platform: device
    domain: shelly
    type: long_push
    subtype: button2
    device_id: !input shelly_devices
    id: long
  - platform: device
    domain: shelly
    type: btn_up
    subtype: button2
    device_id: !input shelly_devices
    id: btn_up
  - platform: device
    domain: shelly
    type: btn_down
    subtype: button2
    device_id: !input shelly_devices
    id: btn_down

action:
  - choose:
      - conditions:
          - condition: trigger
            id: single
        sequence: !input single_press_action
      - conditions:
          - condition: trigger
            id: double
        sequence: !input double_press_action
      - conditions:
          - condition: trigger
            id: triple
        sequence: !input triple_press_action
      - conditions:
          - condition: trigger
            id: long
        sequence: !input long_press_action
      - conditions:
          - condition: trigger
            id: btn_up
        sequence: !input btn_up_action
      - conditions:
          - condition: trigger
            id: btn_down
        sequence: !input btn_down_action
