blueprint:
  name: Shelly 2PM Cover Controls
  description: Control covers using Shelly 2PM buttons with all available actions - single press, double press, triple press, long press, button up, and button down.
  domain: automation
  input:
    shelly_device:
      name: Shelly Device
      description: Select the Shelly device to use for button control
      selector:
        device:
          integration: shelly
          multiple: false

    # Button 1 Actions
    button_1_single_press_action:
      name: Button 1 - Single Press Action
      description: Action to run on single press of button 1
      default: []
      selector:
        action: {}
    button_1_double_press_action:
      name: Button 1 - Double Press Action
      description: Action to run on double press of button 1
      default: []
      selector:
        action: {}
    button_1_triple_press_action:
      name: Button 1 - Triple Press Action
      description: Action to run on triple press of button 1
      default: []
      selector:
        action: {}
    button_1_long_press_action:
      name: Button 1 - Long Press Action
      description: Action to run on long press of button 1
      default: []
      selector:
        action: {}
    button_1_up_action:
      name: Button 1 - Button Up Action
      description: Action to run when button 1 is released
      default: []
      selector:
        action: {}
    button_1_down_action:
      name: Button 1 - Button Down Action
      description: Action to run when button 1 is pressed down
      default: []
      selector:
        action: {}

    # Button 2 Actions
    button_2_single_press_action:
      name: Button 2 - Single Press Action
      description: Action to run on single press of button 2
      default: []
      selector:
        action: {}
    button_2_double_press_action:
      name: Button 2 - Double Press Action
      description: Action to run on double press of button 2
      default: []
      selector:
        action: {}
    button_2_triple_press_action:
      name: Button 2 - Triple Press Action
      description: Action to run on triple press of button 2
      default: []
      selector:
        action: {}
    button_2_long_press_action:
      name: Button 2 - Long Press Action
      description: Action to run on long press of button 2
      default: []
      selector:
        action: {}
    button_2_up_action:
      name: Button 2 - Button Up Action
      description: Action to run when button 2 is released
      default: []
      selector:
        action: {}
    button_2_down_action:
      name: Button 2 - Button Down Action
      description: Action to run when button 2 is pressed down
      default: []
      selector:
        action: {}

mode: single

trigger:
  # Button 1 Triggers
  - platform: device
    domain: shelly
    type: single_push
    subtype: button1
    device_id: !input shelly_device
    id: button_1_single
  - platform: device
    domain: shelly
    type: double_push
    subtype: button1
    device_id: !input shelly_device
    id: button_1_double
  - platform: device
    domain: shelly
    type: triple_push
    subtype: button1
    device_id: !input shelly_device
    id: button_1_triple
  - platform: device
    domain: shelly
    type: long_push
    subtype: button1
    device_id: !input shelly_device
    id: button_1_long
  - platform: device
    domain: shelly
    type: btn_up
    subtype: button1
    device_id: !input shelly_device
    id: button_1_up
  - platform: device
    domain: shelly
    type: btn_down
    subtype: button1
    device_id: !input shelly_device
    id: button_1_down

  # Button 2 Triggers
  - platform: device
    domain: shelly
    type: single_push
    subtype: button2
    device_id: !input shelly_device
    id: button_2_single
  - platform: device
    domain: shelly
    type: double_push
    subtype: button2
    device_id: !input shelly_device
    id: button_2_double
  - platform: device
    domain: shelly
    type: triple_push
    subtype: button2
    device_id: !input shelly_device
    id: button_2_triple
  - platform: device
    domain: shelly
    type: long_push
    subtype: button2
    device_id: !input shelly_device
    id: button_2_long
  - platform: device
    domain: shelly
    type: btn_up
    subtype: button2
    device_id: !input shelly_device
    id: button_2_up
  - platform: device
    domain: shelly
    type: btn_down
    subtype: button2
    device_id: !input shelly_device
    id: button_2_down

action:
  - choose:
      # Button 1 Actions
      - conditions:
          - condition: trigger
            id: button_1_single
        sequence: !input button_1_single_press_action
      - conditions:
          - condition: trigger
            id: button_1_double
        sequence: !input button_1_double_press_action
      - conditions:
          - condition: trigger
            id: button_1_triple
        sequence: !input button_1_triple_press_action
      - conditions:
          - condition: trigger
            id: button_1_long
        sequence: !input button_1_long_press_action
      - conditions:
          - condition: trigger
            id: button_1_up
        sequence: !input button_1_up_action
      - conditions:
          - condition: trigger
            id: button_1_down
        sequence: !input button_1_down_action

      # Button 2 Actions
      - conditions:
          - condition: trigger
            id: button_2_single
        sequence: !input button_2_single_press_action
      - conditions:
          - condition: trigger
            id: button_2_double
        sequence: !input button_2_double_press_action
      - conditions:
          - condition: trigger
            id: button_2_triple
        sequence: !input button_2_triple_press_action
      - conditions:
          - condition: trigger
            id: button_2_long
        sequence: !input button_2_long_press_action
      - conditions:
          - condition: trigger
            id: button_2_up
        sequence: !input button_2_up_action
      - conditions:
          - condition: trigger
            id: button_2_down
        sequence: !input button_2_down_action
